"""
schwab_step5_technicals.py
---
Purpose
    This module performs technical analysis on a stock's historical price data. Specifically, it calculates "Classical Floor Pivots" (support and resistance levels used by day traders) based on the most recent day's high, low, and close prices. It also acts as a coordinator, handing off data to a separate calculator to figure out "Realized Volatility" (how wildly the stock has actually been swinging).

Prerequisites
    - A populated `MarketDataContext` object containing historical price data (candles).
    - An instance of the `Step5RealizedVolCalculator` to handle the heavy math for volatility.

What this module does
    1. Checks if the historical price data table exists and has the required columns (open, high, low, close, datetime).
    2. Drops any rows with missing data and sorts them chronologically.
    3. Checks if the asset looks like a Mutual Fund (where the high and low prices are identical almost every day because it only prices once at close).
    4. Evaluates if the stock price is too close to zero (sub-penny), which breaks volatility math.
    5. Delegates the complex realized volatility calculation to the provided `rv_calc` if the data is good.
    6. Calculates traditional Pivot Points (P, R1, R2, R3, S1, S2, S3) using the last available price candle.
    7. Returns a combined dictionary containing both the pivot points and the volatility metrics.

Configuration knobs
    None. The 0.80 (80%) threshold for detecting mutual funds and the 0.01 (1 cent) threshold for sub-penny stocks are hardcoded.

Outputs
    Returns a dictionary with two main sections:
    - `classical_floor_pivots`: A dictionary containing calculated pivot and support/resistance levels, and a status state.
    - `realized_volatility`: A dictionary containing volatility calculations generated by the injected `rv_calc`.

Notes
    This module delegates the heaviest math (Realized Volatility) to another file to keep things clean. It also specifically protects against "NAV-based" assets (Mutual Funds) which have fake intraday highs and lows that would ruin technical analysis.
"""
# Tell Python to allow newer style hints (annotations) for variable types, even in older Python versions
from __future__ import annotations

# Import typing helpers to describe that variables can be Any type or Dictionaries
from typing import Any, Dict

# Import the main context object that holds all the loaded data about a stock
from schwab_marketdata_context import MarketDataContext
# Import the separate calculator responsible for calculating historical (realized) volatility
from schwab_step5_realized_vol import Step5RealizedVolCalculator
# Import a utility function to safely turn text/messy data into a clean decimal number
from schwab_utils import safe_float


# Define a class that handles Step 5 Technical calculations (Pivots and coordinating Volatility)
class Step5TechnicalsCalculator:

    # The initialization method that runs when a new Step5TechnicalsCalculator is created
    def __init__(self, ctx: MarketDataContext, rv_calc: Step5RealizedVolCalculator):
        # Store the provided market data context object
        self.ctx = ctx
        # Store the provided realized volatility calculator object
        self.rv_calc = rv_calc

    # Define the main calculate method that returns a dictionary of results
    def calculate(self) -> Dict[str, Any]:
        # Set up default failure responses for pivots and volatility, assuming we don't have enough data
        pivots = {"state": "UNKNOWN", "reason": "insufficient_ohlc_bars"}
        rv = {"state": "UNKNOWN", "reason": "insufficient_ohlc_bars"}

        # Check if the historical price table (ph_df) is completely empty
        if self.ctx.ph_df.empty:
            # If it is, just return the default failure responses immediately
            return {"classical_floor_pivots": pivots, "realized_volatility": rv}

        # Check if the historical price table is missing the 'datetime' column
        if "datetime" not in self.ctx.ph_df.columns:
            # If it is, return a specific failure reason explaining the missing column
            return {
                "classical_floor_pivots": {"state": "UNKNOWN", "reason": "missing_datetime_column"},
                "realized_volatility": {"state": "UNKNOWN", "reason": "missing_datetime_column"},
            }

        # Clean up the historical price data: drop any rows that are missing critical price or time data, and sort them oldest to newest
        clean_bars = self.ctx.ph_df.dropna(
            subset=["open", "high", "low", "close", "datetime"]
        ).sort_values("datetime")

        # Check if cleaning the data resulted in an empty table
        if clean_bars.empty:
            # If so, return the default failure responses
            return {"classical_floor_pivots": pivots, "realized_volatility": rv}

        # Extract the entire column of closing prices
        c_series = clean_bars["close"]
        # Extract the entire column of low prices
        l_series = clean_bars["low"]
        # Extract the entire column of high prices
        h_series = clean_bars["high"]

        # Check if this asset acts like a Mutual Fund (NAV-based).
        # Mutual funds don't trade during the day, so their 'high' and 'low' prices are usually exactly the same.
        # If the high equals the low on at least 80% (0.80) of the days, we flag it.
        is_nav_flat = (h_series == l_series).mean() >= 0.80

        # Check if any closing price or low price in the history dropped to 1 penny ($0.01) or less
        if (c_series <= 0.01).any() or (l_series <= 0.01).any():
            # If so, we can't calculate volatility because dividing by numbers near zero breaks the math formulas
            rv = {
                "state": "UNKNOWN",
                "reason": "sub_cent_zero_price_bars_unsuitable_for_diffusion_estimators",
            }
        # If it's a mutual fund (flat NAV)
        elif is_nav_flat:
            # We can't calculate volatility because there are no intraday price swings to measure
            rv = {
                "state": "NOT_APPLICABLE_NAV_BASED_ASSET",
                "reason": "intraday_hl_identical_nav_bars",
            }
        # If the data is good and it's a normal stock
        else:
            # Hand the clean data over to the separate Realized Volatility calculator and store its results
            rv = self.rv_calc.calculate_suite(clean_bars)

        # Now, figure out the Pivot Points
        # If it's a mutual fund (flat NAV)
        if is_nav_flat:
            # Pivots don't make sense for mutual funds, so return a failure explaining why
            pivots = {
                "state": "NOT_APPLICABLE_NAV_BASED_ASSET",
                "reason": "intraday_hl_identical_nav_bars",
            }
        # If it's a normal stock
        else:
            # Grab the very last (most recent) row of price data
            last_bar = clean_bars.iloc[-1]
            # Safely extract the high, low, and close prices from that last row
            h, l, c = safe_float(last_bar["high"]), safe_float(last_bar["low"]), safe_float(last_bar["close"])

            # Make sure all three prices actually exist (are not None) and are positive numbers
            if h is not None and l is not None and c is not None and h > 0 and l > 0 and c > 0:
                # Calculate the central Pivot Point (P) as the average of the high, low, and close
                p = (h + l + c) / 3.0

                # Make sure the calculated pivot isn't absurdly small (less than half a penny)
                if p >= 0.005:
                    # Calculate and store the standard Floor Pivot levels, rounding everything to 2 decimal places (dollars and cents)
                    pivots = {
                        "Pivot": round(p, 2),                   # The central pivot point
                        "R1": round((2 * p) - l, 2),            # Resistance level 1
                        "R2": round(p + (h - l), 2),            # Resistance level 2
                        "R3": round(p + 2 * (h - l), 2),        # Resistance level 3
                        "S1": round((2 * p) - h, 2),            # Support level 1
                        "S2": round(p - (h - l), 2),            # Support level 2
                        "S3": round(p - 2 * (h - l), 2),        # Support level 3
                        "state": "CALCULATED",                  # Mark as successfully calculated
                    }
                # If the pivot was too small to be meaningful
                else:
                    pivots = {"state": "UNKNOWN", "reason": "candle_prices_non_positive"}
            # If the prices didn't exist or were negative
            else:
                pivots = {"state": "UNKNOWN", "reason": "candle_prices_non_positive"}

        # Return the combined dictionary containing both the pivot and volatility results
        return {"classical_floor_pivots": pivots, "realized_volatility": rv}