# Filename.py: schwab_underlying_grounding.py
# Purpose: This module is part of the schwab integration and provides market data functionality.
# Prerequisites: None.
# What this module does:
# 1. Provide methods to support schwab data processing.
# Configuration knobs: None.
# Outputs: Various schwab datatypes and integration results.
# Notes: None.

# Filename.py: schwab_underlying_grounding.py
# Purpose: This module is part of the schwab integration and provides market data functionality.
# Prerequisites: None.
# What this module does:
# 1. Provide methods to support schwab data processing.
# Configuration knobs: None.
# Outputs: Various schwab datatypes and integration results.
# Notes: None.

"""
schwab_underlying_grounding.py

Orchestrator: fetches the vendor quote envelope and assembles the canonical
phase_0 / step_1 / short_locate / liquidity grounding payload.

Inline classification and resolution blocks have been replaced by calls into
the pure resolvers (Batch 2). Bodies of those blocks are unchanged; only the
call sites differ. Statement order matches the original source order.

Extracted from schwab_raw_marketdata.py (no logic change).
"""
# Explain this line: from __future__ import annotations...
# Line: from __future__ import annotations
from __future__ import annotations

# Explain this line: import logging...
# Line: import logging
import logging
# Explain this line: from datetime import datetime, timezone...
# Line: from datetime import datetime, timezone
from datetime import datetime, timezone
# Explain this line: from typing import Any, Dict...
# Line: from typing import Any, Dict
from typing import Any, Dict
# Explain this line: from zoneinfo import ZoneInfo...
# Line: from zoneinfo import ZoneInfo
from zoneinfo import ZoneInfo

# Explain this line: from schwab_utils import safe_float, val...
# Line: from schwab_utils import safe_float, validate_symb
from schwab_utils import safe_float, validate_symbol

# Explain this line: from schwab_vendor_resilience import par...
# Line: from schwab_vendor_resilience import parse_client_
from schwab_vendor_resilience import parse_client_response, retry_vendor_call
# Explain this line: from schwab_grounding_schema import buil...
# Line: from schwab_grounding_schema import build_halted_g
from schwab_grounding_schema import build_halted_grounding
# Explain this line: from schwab_instrument_classification im...
# Line: from schwab_instrument_classification import (
from schwab_instrument_classification import (
    # Explain this line: classify_desc_pooled_match,...
    # Line: classify_desc_pooled_match,
    classify_desc_pooled_match,
    # Explain this line: classify_foreign_adr,...
    # Line: classify_foreign_adr,
    classify_foreign_adr,
    # Explain this line: classify_foreign_country,...
    # Line: classify_foreign_country,
    classify_foreign_country,
    # Explain this line: classify_fund_type,...
    # Line: classify_fund_type,
    classify_fund_type,
    # Explain this line: classify_mutual_fund,...
    # Line: classify_mutual_fund,
    classify_mutual_fund,
    # Explain this line: classify_quote_age,...
    # Line: classify_quote_age,
    classify_quote_age,
    # Explain this line: classify_structural_wrapper,...
    # Line: classify_structural_wrapper,
    classify_structural_wrapper,
    # Explain this line: classify_warrant,...
    # Line: classify_warrant,
    classify_warrant,
    # Explain this line: functionally_zero,...
    # Line: functionally_zero,
    functionally_zero,
# Explain this line: )...
# Line: )
)
# Explain this line: from schwab_fundamental_resolvers import...
# Line: from schwab_fundamental_resolvers import (
from schwab_fundamental_resolvers import (
    # Explain this line: resolve_dividend,...
    # Line: resolve_dividend,
    resolve_dividend,
    # Explain this line: resolve_margin_sanity,...
    # Line: resolve_margin_sanity,
    resolve_margin_sanity,
    # Explain this line: resolve_pe_eps,...
    # Line: resolve_pe_eps,
    resolve_pe_eps,
    # Explain this line: resolve_shares_outstanding,...
    # Line: resolve_shares_outstanding,
    resolve_shares_outstanding,
# Explain this line: )...
# Line: )
)
# Explain this line: from schwab_short_locate import resolve_...
# Line: from schwab_short_locate import resolve_short_loca
from schwab_short_locate import resolve_short_locate
# Explain this line: from schwab_liquidity_book import resolv...
# Line: from schwab_liquidity_book import resolve_liquidit
from schwab_liquidity_book import resolve_liquidity

# Explain this line: logger = logging.getLogger("schwab_raw_m...
# Line: logger = logging.getLogger("schwab_raw_marketdata"
logger = logging.getLogger("schwab_raw_marketdata")
# Explain this line: logger.addHandler(logging.NullHandler())...
# Line: logger.addHandler(logging.NullHandler())
logger.addHandler(logging.NullHandler())


# Explain this line: def extract_strict_underlying_data(...
# Line: def extract_strict_underlying_data(
def extract_strict_underlying_data(
    # Explain this line: client: Any, symbol: str, tz_et: ZoneInf...
    # Line: client: Any, symbol: str, tz_et: ZoneInfo
    client: Any, symbol: str, tz_et: ZoneInfo
# Explain this line: ) -> Dict[str, Any]:...
# Line: ) -> Dict[str, Any]:
) -> Dict[str, Any]:
    # Explain this line: clean_sym = validate_symbol(symbol)...
    # Line: clean_sym = validate_symbol(symbol)
    clean_sym = validate_symbol(symbol)

    # Explain this line: @retry_vendor_call(max_retries=3, base_d...
    # Line: @retry_vendor_call(max_retries=3, base_delay=0.2)
    @retry_vendor_call(max_retries=3, base_delay=0.2)
    # Explain this line: def _fetch_quote(sym: str) -> Any:...
    # Line: def _fetch_quote(sym: str) -> Any:
    def _fetch_quote(sym: str) -> Any:
        # Explain this line: return client.get_quote(sym)...
        # Line: return client.get_quote(sym)
        return client.get_quote(sym)

    # Explain this line: try:...
    # Line: try:
    try:
        # Explain this line: res_dict = parse_client_response(_fetch_...
        # Line: res_dict = parse_client_response(_fetch_quote(clea
        res_dict = parse_client_response(_fetch_quote(clean_sym))
    # Explain this line: except Exception as e:...
    # Line: except Exception as e:
    except Exception as e:
        # Explain this line: logger.warning("Quote fetch raised for %...
        # Line: logger.warning("Quote fetch raised for %s: %s", cl
        logger.warning("Quote fetch raised for %s: %s", clean_sym, e)
        # Explain this line: res_dict = None...
        # Line: res_dict = None
        res_dict = None

    # Explain this line: if not isinstance(res_dict, dict) or not...
    # Line: if not isinstance(res_dict, dict) or not res_dict:
    if not isinstance(res_dict, dict) or not res_dict:
        # Explain this line: return build_halted_grounding(clean_sym,...
        # Line: return build_halted_grounding(clean_sym, tz_et, No
        return build_halted_grounding(clean_sym, tz_et, None, None)

    # Explain this line: candidate = (...
    # Line: candidate = (
    candidate = (
        # Explain this line: res_dict.get(clean_sym)...
        # Line: res_dict.get(clean_sym)
        res_dict.get(clean_sym)
        # Explain this line: or res_dict.get(symbol)...
        # Line: or res_dict.get(symbol)
        or res_dict.get(symbol)
        # Explain this line: or res_dict.get(symbol.lower())...
        # Line: or res_dict.get(symbol.lower())
        or res_dict.get(symbol.lower())
        # Explain this line: or res_dict...
        # Line: or res_dict
        or res_dict
    # Explain this line: )...
    # Line: )
    )
    # Explain this line: if isinstance(candidate, dict):...
    # Line: if isinstance(candidate, dict):
    if isinstance(candidate, dict):
        # Explain this line: if clean_sym in candidate and isinstance...
        # Line: if clean_sym in candidate and isinstance(candidate
        if clean_sym in candidate and isinstance(candidate[clean_sym], dict):
            # Explain this line: candidate = candidate[clean_sym]...
            # Line: candidate = candidate[clean_sym]
            candidate = candidate[clean_sym]
        # Explain this line: elif symbol in candidate and isinstance(...
        # Line: elif symbol in candidate and isinstance(candidate[
        elif symbol in candidate and isinstance(candidate[symbol], dict):
            # Explain this line: candidate = candidate[symbol]...
            # Line: candidate = candidate[symbol]
            candidate = candidate[symbol]
    # Explain this line: data = candidate if isinstance(candidate...
    # Line: data = candidate if isinstance(candidate, dict) el
    data = candidate if isinstance(candidate, dict) else {}

    # Explain this line: if not data:...
    # Line: if not data:
    if not data:
        # Explain this line: return build_halted_grounding(clean_sym,...
        # Line: return build_halted_grounding(clean_sym, tz_et, No
        return build_halted_grounding(clean_sym, tz_et, None, None)

    # Explain this line: ref = data.get("reference", {}) if isins...
    # Line: ref = data.get("reference", {}) if isinstance(data
    ref = data.get("reference", {}) if isinstance(data.get("reference"), dict) else {}
    # Explain this line: quote = data.get("quote", {}) if isinsta...
    # Line: quote = data.get("quote", {}) if isinstance(data.g
    quote = data.get("quote", {}) if isinstance(data.get("quote"), dict) else {}
    # Explain this line: fund = data.get("fundamental", {}) if is...
    # Line: fund = data.get("fundamental", {}) if isinstance(d
    fund = data.get("fundamental", {}) if isinstance(data.get("fundamental"), dict) else {}
    # Explain this line: asset_sub = str(ref.get("assetSubType", ...
    # Line: asset_sub = str(ref.get("assetSubType", "") or "")
    asset_sub = str(ref.get("assetSubType", "") or "").upper()
    # Explain this line: asset_main = str(ref.get("assetMainType"...
    # Line: asset_main = str(ref.get("assetMainType", "") or "
    asset_main = str(ref.get("assetMainType", "") or "").upper()
    # Explain this line: desc = str(ref.get("description", "") or...
    # Line: desc = str(ref.get("description", "") or "").upper
    desc = str(ref.get("description", "") or "").upper()

    # Explain this line: if not quote and not fund:...
    # Line: if not quote and not fund:
    if not quote and not fund:
        # Explain this line: return build_halted_grounding(clean_sym,...
        # Line: return build_halted_grounding(clean_sym, tz_et, No
        return build_halted_grounding(clean_sym, tz_et, None, None)

    # Explain this line: raw_shares = safe_float(fund.get("shares...
    # Line: raw_shares = safe_float(fund.get("sharesOutstandin
    raw_shares = safe_float(fund.get("sharesOutstanding"))

    # --- Classification (Batch 2) — original source position ---
    # Explain this line: is_warrant = classify_warrant(asset_sub,...
    # Line: is_warrant = classify_warrant(asset_sub, asset_mai
    is_warrant = classify_warrant(asset_sub, asset_main, desc, clean_sym)
    # Explain this line: is_mutual_fund = classify_mutual_fund(as...
    # Line: is_mutual_fund = classify_mutual_fund(asset_sub, a
    is_mutual_fund = classify_mutual_fund(asset_sub, asset_main, clean_sym)
    # Explain this line: is_fund_type = classify_fund_type(asset_...
    # Line: is_fund_type = classify_fund_type(asset_sub, asset
    is_fund_type = classify_fund_type(asset_sub, asset_main, is_mutual_fund)
    # Explain this line: desc_pooled_match = classify_desc_pooled...
    # Line: desc_pooled_match = classify_desc_pooled_match(des
    desc_pooled_match = classify_desc_pooled_match(desc)
    # Explain this line: is_structural_wrapper = classify_structu...
    # Line: is_structural_wrapper = classify_structural_wrappe
    is_structural_wrapper = classify_structural_wrapper(
        # Explain this line: is_warrant, is_fund_type, desc_pooled_ma...
        # Line: is_warrant, is_fund_type, desc_pooled_match
        is_warrant, is_fund_type, desc_pooled_match
    # Explain this line: )...
    # Line: )
    )

    # Explain this line: last_p = safe_float(quote.get("lastPrice...
    # Line: last_p = safe_float(quote.get("lastPrice"))
    last_p = safe_float(quote.get("lastPrice"))
    # Explain this line: close_p = safe_float(quote.get("closePri...
    # Line: close_p = safe_float(quote.get("closePrice"))
    close_p = safe_float(quote.get("closePrice"))
    # Explain this line: q_time_raw = quote.get("quoteTime", 0)...
    # Line: q_time_raw = quote.get("quoteTime", 0)
    q_time_raw = quote.get("quoteTime", 0)

    # Explain this line: if q_time_raw:...
    # Line: if q_time_raw:
    if q_time_raw:
        # Explain this line: now_ts = datetime.now(timezone.utc).time...
        # Line: now_ts = datetime.now(timezone.utc).timestamp()
        now_ts = datetime.now(timezone.utc).timestamp()
        # Explain this line: quote_ts = q_time_raw / 1000.0...
        # Line: quote_ts = q_time_raw / 1000.0
        quote_ts = q_time_raw / 1000.0
        # Explain this line: q_time_iso = (...
        # Line: q_time_iso = (
        q_time_iso = (
            # Explain this line: datetime.fromtimestamp(quote_ts, tz=time...
            # Line: datetime.fromtimestamp(quote_ts, tz=timezone.utc)
            datetime.fromtimestamp(quote_ts, tz=timezone.utc)
            # Explain this line: .astimezone(tz_et)...
            # Line: .astimezone(tz_et)
            .astimezone(tz_et)
            # Explain this line: .isoformat()...
            # Line: .isoformat()
            .isoformat()
        # Explain this line: )...
        # Line: )
        )
        # Explain this line: q_age = max(0.0, round(now_ts - quote_ts...
        # Line: q_age = max(0.0, round(now_ts - quote_ts, 2))
        q_age = max(0.0, round(now_ts - quote_ts, 2))
    # Explain this line: else:...
    # Line: else:
    else:
        # Explain this line: q_time_iso = None...
        # Line: q_time_iso = None
        q_time_iso = None
        # Explain this line: q_age = None...
        # Line: q_age = None
        q_age = None

    # Explain this line: is_halted_or_unquoted = (...
    # Line: is_halted_or_unquoted = (
    is_halted_or_unquoted = (
        # Explain this line: (functionally_zero(last_p) and functiona...
        # Line: (functionally_zero(last_p) and functionally_zero(c
        (functionally_zero(last_p) and functionally_zero(close_p))
        # Explain this line: or (desc == "" and last_p is None)...
        # Line: or (desc == "" and last_p is None)
        or (desc == "" and last_p is None)
    # Explain this line: )...
    # Line: )
    )

    # Explain this line: if is_halted_or_unquoted:...
    # Line: if is_halted_or_unquoted:
    if is_halted_or_unquoted:
        # Explain this line: q_class = "UNAVAILABLE_ASSET_HALTED_OR_U...
        # Line: q_class = "UNAVAILABLE_ASSET_HALTED_OR_UNQUOTED"
        q_class = "UNAVAILABLE_ASSET_HALTED_OR_UNQUOTED"
    # Explain this line: else:...
    # Line: else:
    else:
        # Explain this line: q_class = classify_quote_age(q_age)...
        # Line: q_class = classify_quote_age(q_age)
        q_class = classify_quote_age(q_age)

    # Explain this line: raw_pe = safe_float(fund.get("peRatio"))...
    # Line: raw_pe = safe_float(fund.get("peRatio"))
    raw_pe = safe_float(fund.get("peRatio"))
    # Explain this line: raw_eps = safe_float(fund.get("eps"))...
    # Line: raw_eps = safe_float(fund.get("eps"))
    raw_eps = safe_float(fund.get("eps"))
    # Explain this line: raw_div_amt = safe_float(fund.get("divAm...
    # Line: raw_div_amt = safe_float(fund.get("divAmount"))
    raw_div_amt = safe_float(fund.get("divAmount"))
    # Explain this line: raw_div_y = safe_float(fund.get("divYiel...
    # Line: raw_div_y = safe_float(fund.get("divYield"))
    raw_div_y = safe_float(fund.get("divYield"))
    # Explain this line: raw_div_freq = safe_float(fund.get("divF...
    # Line: raw_div_freq = safe_float(fund.get("divFreq"))
    raw_div_freq = safe_float(fund.get("divFreq"))

    # Explain this line: country = str(...
    # Line: country = str(
    country = str(
        # Explain this line: ref.get("country")...
        # Line: ref.get("country")
        ref.get("country")
        # Explain this line: or quote.get("country")...
        # Line: or quote.get("country")
        or quote.get("country")
        # Explain this line: or fund.get("country")...
        # Line: or fund.get("country")
        or fund.get("country")
        # Explain this line: or ""...
        # Line: or ""
        or ""
    # Explain this line: ).strip().upper()...
    # Line: ).strip().upper()
    ).strip().upper()
    # Explain this line: is_foreign_country = classify_foreign_co...
    # Line: is_foreign_country = classify_foreign_country(coun
    is_foreign_country = classify_foreign_country(country)
    # Explain this line: is_foreign_adr = classify_foreign_adr(de...
    # Line: is_foreign_adr = classify_foreign_adr(desc, asset_
    is_foreign_adr = classify_foreign_adr(desc, asset_sub, is_foreign_country)

    # --- Resolvers (Batch 2) ---
    # Explain this line: shares_val, shares_state = resolve_share...
    # Line: shares_val, shares_state = resolve_shares_outstand
    shares_val, shares_state = resolve_shares_outstanding(
        # Explain this line: raw_shares,...
        # Line: raw_shares,
        raw_shares,
        # Explain this line: is_halted_or_unquoted,...
        # Line: is_halted_or_unquoted,
        is_halted_or_unquoted,
        # Explain this line: is_warrant,...
        # Line: is_warrant,
        is_warrant,
        # Explain this line: is_structural_wrapper,...
        # Line: is_structural_wrapper,
        is_structural_wrapper,
        # Explain this line: is_foreign_adr,...
        # Line: is_foreign_adr,
        is_foreign_adr,
    # Explain this line: )...
    # Line: )
    )

    # Explain this line: pe_val, pe_state, eps_val, eps_state = r...
    # Line: pe_val, pe_state, eps_val, eps_state = resolve_pe_
    pe_val, pe_state, eps_val, eps_state = resolve_pe_eps(
        # Explain this line: raw_pe,...
        # Line: raw_pe,
        raw_pe,
        # Explain this line: raw_eps,...
        # Line: raw_eps,
        raw_eps,
        # Explain this line: is_halted_or_unquoted,...
        # Line: is_halted_or_unquoted,
        is_halted_or_unquoted,
        # Explain this line: is_warrant,...
        # Line: is_warrant,
        is_warrant,
        # Explain this line: is_structural_wrapper,...
        # Line: is_structural_wrapper,
        is_structural_wrapper,
        # Explain this line: is_foreign_adr,...
        # Line: is_foreign_adr,
        is_foreign_adr,
    # Explain this line: )...
    # Line: )
    )

    # Explain this line: raw_div_y, div_y_basis, raw_div_freq, di...
    # Line: raw_div_y, div_y_basis, raw_div_freq, div_freq_sta
    raw_div_y, div_y_basis, raw_div_freq, div_freq_state = resolve_dividend(
        # Explain this line: raw_div_y, raw_div_amt, raw_div_freq, is...
        # Line: raw_div_y, raw_div_amt, raw_div_freq, is_halted_or
        raw_div_y, raw_div_amt, raw_div_freq, is_halted_or_unquoted
    # Explain this line: )...
    # Line: )
    )

    # Explain this line: net_m = safe_float(fund.get("netProfitMa...
    # Line: net_m = safe_float(fund.get("netProfitMarginTTM"))
    net_m = safe_float(fund.get("netProfitMarginTTM"))
    # Explain this line: op_m = safe_float(fund.get("operatingMar...
    # Line: op_m = safe_float(fund.get("operatingMarginTTM"))
    op_m = safe_float(fund.get("operatingMarginTTM"))
    # Explain this line: gross_m = safe_float(fund.get("grossMarg...
    # Line: gross_m = safe_float(fund.get("grossMarginTTM"))
    gross_m = safe_float(fund.get("grossMarginTTM"))

    # Explain this line: margin_suspect, margin_reason, margin_st...
    # Line: margin_suspect, margin_reason, margin_state = reso
    margin_suspect, margin_reason, margin_state = resolve_margin_sanity(net_m, op_m)

    # Explain this line: short_dict = resolve_short_locate(ref, q...
    # Line: short_dict = resolve_short_locate(ref, quote, is_h
    short_dict = resolve_short_locate(ref, quote, is_halted_or_unquoted)

    # Explain this line: liq_dict = resolve_liquidity(quote, fund...
    # Line: liq_dict = resolve_liquidity(quote, fund, is_mutua
    liq_dict = resolve_liquidity(quote, fund, is_mutual_fund, is_halted_or_unquoted)

    # --- Assembly tail (verbatim) ---
    # Explain this line: fund_dict: Dict[str, Any] = {...
    # Line: fund_dict: Dict[str, Any] = {
    fund_dict: Dict[str, Any] = {
        # Explain this line: "beta": safe_float(fund.get("beta")),...
        # Line: "beta": safe_float(fund.get("beta")),
        "beta": safe_float(fund.get("beta")),
        # Explain this line: "beta_state": (...
        # Line: "beta_state": (
        "beta_state": (
            # Explain this line: "AS_REPORTED" if fund.get("beta") is not...
            # Line: "AS_REPORTED" if fund.get("beta") is not None else
            "AS_REPORTED" if fund.get("beta") is not None else "VENDOR_UNAVAILABLE"
        # Explain this line: ),...
        # Line: ),
        ),
        # Explain this line: "peRatio": pe_val,...
        # Line: "peRatio": pe_val,
        "peRatio": pe_val,
        # Explain this line: "peRatio_state": pe_state,...
        # Line: "peRatio_state": pe_state,
        "peRatio_state": pe_state,
        # Explain this line: "pegRatio": safe_float(fund.get("pegRati...
        # Line: "pegRatio": safe_float(fund.get("pegRatio")),
        "pegRatio": safe_float(fund.get("pegRatio")),
        # Explain this line: "pegRatio_state": (...
        # Line: "pegRatio_state": (
        "pegRatio_state": (
            # Explain this line: "AS_REPORTED"...
            # Line: "AS_REPORTED"
            "AS_REPORTED"
            # Explain this line: if fund.get("pegRatio") is not None...
            # Line: if fund.get("pegRatio") is not None
            if fund.get("pegRatio") is not None
            # Explain this line: else "VENDOR_UNAVAILABLE"...
            # Line: else "VENDOR_UNAVAILABLE"
            else "VENDOR_UNAVAILABLE"
        # Explain this line: ),...
        # Line: ),
        ),
        # Explain this line: "pcfRatio": safe_float(fund.get("pcfRati...
        # Line: "pcfRatio": safe_float(fund.get("pcfRatio")),
        "pcfRatio": safe_float(fund.get("pcfRatio")),
        # Explain this line: "pcfRatio_state": (...
        # Line: "pcfRatio_state": (
        "pcfRatio_state": (
            # Explain this line: "AS_REPORTED"...
            # Line: "AS_REPORTED"
            "AS_REPORTED"
            # Explain this line: if fund.get("pcfRatio") is not None...
            # Line: if fund.get("pcfRatio") is not None
            if fund.get("pcfRatio") is not None
            # Explain this line: else "VENDOR_UNAVAILABLE"...
            # Line: else "VENDOR_UNAVAILABLE"
            else "VENDOR_UNAVAILABLE"
        # Explain this line: ),...
        # Line: ),
        ),
        # Explain this line: "pbRatio": safe_float(fund.get("pbRatio"...
        # Line: "pbRatio": safe_float(fund.get("pbRatio")),
        "pbRatio": safe_float(fund.get("pbRatio")),
        # Explain this line: "totalDebtToEquity": safe_float(fund.get...
        # Line: "totalDebtToEquity": safe_float(fund.get("totalDeb
        "totalDebtToEquity": safe_float(fund.get("totalDebtToEquity")),
        # Explain this line: "totalDebtToEquity_basis": "VENDOR_RAW_U...
        # Line: "totalDebtToEquity_basis": "VENDOR_RAW_UNVERIFIED"
        "totalDebtToEquity_basis": "VENDOR_RAW_UNVERIFIED",
        # Explain this line: "grossMarginTTM": gross_m,...
        # Line: "grossMarginTTM": gross_m,
        "grossMarginTTM": gross_m,
        # Explain this line: "netProfitMarginTTM": net_m,...
        # Line: "netProfitMarginTTM": net_m,
        "netProfitMarginTTM": net_m,
        # Explain this line: "operatingMarginTTM": op_m,...
        # Line: "operatingMarginTTM": op_m,
        "operatingMarginTTM": op_m,
        # Explain this line: "margin_fields_suspect": margin_suspect,...
        # Line: "margin_fields_suspect": margin_suspect,
        "margin_fields_suspect": margin_suspect,
        # Explain this line: "margin_fields_suspect_reason": margin_r...
        # Line: "margin_fields_suspect_reason": margin_reason,
        "margin_fields_suspect_reason": margin_reason,
        # Explain this line: "margin_fields_suspect_state": margin_st...
        # Line: "margin_fields_suspect_state": margin_state,
        "margin_fields_suspect_state": margin_state,
        # Explain this line: "returnOnEquity": safe_float(fund.get("r...
        # Line: "returnOnEquity": safe_float(fund.get("returnOnEqu
        "returnOnEquity": safe_float(fund.get("returnOnEquity")),
        # Explain this line: "returnOnEquity_state": (...
        # Line: "returnOnEquity_state": (
        "returnOnEquity_state": (
            # Explain this line: "AS_REPORTED"...
            # Line: "AS_REPORTED"
            "AS_REPORTED"
            # Explain this line: if fund.get("returnOnEquity") is not Non...
            # Line: if fund.get("returnOnEquity") is not None
            if fund.get("returnOnEquity") is not None
            # Explain this line: else "VENDOR_UNAVAILABLE"...
            # Line: else "VENDOR_UNAVAILABLE"
            else "VENDOR_UNAVAILABLE"
        # Explain this line: ),...
        # Line: ),
        ),
        # Explain this line: "returnOnAssets": safe_float(fund.get("r...
        # Line: "returnOnAssets": safe_float(fund.get("returnOnAss
        "returnOnAssets": safe_float(fund.get("returnOnAssets")),
        # Explain this line: "returnOnAssets_state": (...
        # Line: "returnOnAssets_state": (
        "returnOnAssets_state": (
            # Explain this line: "AS_REPORTED"...
            # Line: "AS_REPORTED"
            "AS_REPORTED"
            # Explain this line: if fund.get("returnOnAssets") is not Non...
            # Line: if fund.get("returnOnAssets") is not None
            if fund.get("returnOnAssets") is not None
            # Explain this line: else "VENDOR_UNAVAILABLE"...
            # Line: else "VENDOR_UNAVAILABLE"
            else "VENDOR_UNAVAILABLE"
        # Explain this line: ),...
        # Line: ),
        ),
        # Explain this line: "eps": eps_val,...
        # Line: "eps": eps_val,
        "eps": eps_val,
        # Explain this line: "eps_state": eps_state,...
        # Line: "eps_state": eps_state,
        "eps_state": eps_state,
        # Explain this line: "revChangeYear": safe_float(fund.get("re...
        # Line: "revChangeYear": safe_float(fund.get("revChangeYea
        "revChangeYear": safe_float(fund.get("revChangeYear")),
        # Explain this line: "revChangeYear_state": (...
        # Line: "revChangeYear_state": (
        "revChangeYear_state": (
            # Explain this line: "AS_REPORTED"...
            # Line: "AS_REPORTED"
            "AS_REPORTED"
            # Explain this line: if fund.get("revChangeYear") is not None...
            # Line: if fund.get("revChangeYear") is not None
            if fund.get("revChangeYear") is not None
            # Explain this line: else "VENDOR_UNAVAILABLE"...
            # Line: else "VENDOR_UNAVAILABLE"
            else "VENDOR_UNAVAILABLE"
        # Explain this line: ),...
        # Line: ),
        ),
        # Explain this line: "divYield": raw_div_y if raw_div_y is no...
        # Line: "divYield": raw_div_y if raw_div_y is not None els
        "divYield": raw_div_y if raw_div_y is not None else 0.0,
        # Explain this line: "divYield_basis": div_y_basis,...
        # Line: "divYield_basis": div_y_basis,
        "divYield_basis": div_y_basis,
        # Explain this line: "divYield_raw": raw_div_y if raw_div_y i...
        # Line: "divYield_raw": raw_div_y if raw_div_y is not None
        "divYield_raw": raw_div_y if raw_div_y is not None else 0.0,
        # Explain this line: "divAmount": f"${raw_div_amt:.2f}" if ra...
        # Line: "divAmount": f"${raw_div_amt:.2f}" if raw_div_amt
        "divAmount": f"${raw_div_amt:.2f}" if raw_div_amt is not None else "$0.00",
        # Explain this line: "div_amount_basis": "ANNUAL",...
        # Line: "div_amount_basis": "ANNUAL",
        "div_amount_basis": "ANNUAL",
        # Explain this line: "divFreq": raw_div_freq,...
        # Line: "divFreq": raw_div_freq,
        "divFreq": raw_div_freq,
        # Explain this line: "sharesOutstanding": shares_val,...
        # Line: "sharesOutstanding": shares_val,
        "sharesOutstanding": shares_val,
        # Explain this line: "shares_outstanding_state": shares_state...
        # Line: "shares_outstanding_state": shares_state,
        "shares_outstanding_state": shares_state,
        # Explain this line: "marketCap": safe_float(fund.get("market...
        # Line: "marketCap": safe_float(fund.get("marketCap")),
        "marketCap": safe_float(fund.get("marketCap")),
        # Explain this line: "marketCap_unit": "VENDOR_RAW_UNVERIFIED...
        # Line: "marketCap_unit": "VENDOR_RAW_UNVERIFIED",
        "marketCap_unit": "VENDOR_RAW_UNVERIFIED",
    # Explain this line: }...
    # Line: }
    }
    # Explain this line: if div_freq_state:...
    # Line: if div_freq_state:
    if div_freq_state:
        # Explain this line: fund_dict["divFreq_state"] = div_freq_st...
        # Line: fund_dict["divFreq_state"] = div_freq_state
        fund_dict["divFreq_state"] = div_freq_state

    # Explain this line: return {...
    # Line: return {
    return {
        # Explain this line: "phase_0_grounding": {...
        # Line: "phase_0_grounding": {
        "phase_0_grounding": {
            # Explain this line: "symbol": clean_sym,...
            # Line: "symbol": clean_sym,
            "symbol": clean_sym,
            # Explain this line: "company_name": desc,...
            # Line: "company_name": desc,
            "company_name": desc,
            # Explain this line: "lastPrice": f"${last_p:.2f}" if last_p ...
            # Line: "lastPrice": f"${last_p:.2f}" if last_p is not Non
            "lastPrice": f"${last_p:.2f}" if last_p is not None else None,
            # Explain this line: "closePrice": f"${close_p:.2f}" if close...
            # Line: "closePrice": f"${close_p:.2f}" if close_p is not
            "closePrice": f"${close_p:.2f}" if close_p is not None else None,
            # Explain this line: "quoteTime_ISO_ET": q_time_iso,...
            # Line: "quoteTime_ISO_ET": q_time_iso,
            "quoteTime_ISO_ET": q_time_iso,
            # Explain this line: "quote_age_seconds": q_age,...
            # Line: "quote_age_seconds": q_age,
            "quote_age_seconds": q_age,
            # Explain this line: "quote_age_classification": q_class,...
            # Line: "quote_age_classification": q_class,
            "quote_age_classification": q_class,
        # Explain this line: },...
        # Line: },
        },
        # Explain this line: "step_1_fundamentals": fund_dict,...
        # Line: "step_1_fundamentals": fund_dict,
        "step_1_fundamentals": fund_dict,
        # Explain this line: "short_locate_status": short_dict,...
        # Line: "short_locate_status": short_dict,
        "short_locate_status": short_dict,
        # Explain this line: "step_8_and_9_liquidity_and_sizing": liq...
        # Line: "step_8_and_9_liquidity_and_sizing": liq_dict,
        "step_8_and_9_liquidity_and_sizing": liq_dict,
    # Explain this line: }...
    # Line: }
    }